#!/usr/bin/env python3

import json
import os
import sys

rdf = {
  "schema": {
    "version": "v1",
    "name": "register-description-format"
  },
  "root": {
    "version": "v1.0",
    "desc": "svd2rdf Examples",
    "links": [
      { "text": "svd2rdf GitHub", "href": "https://github.com/rfdonnelly/svd2rdf" }
    ],
    "children": []
  },
  "elements": {
  }
}

for path in sys.argv[1:]:
    rdf_filename = os.path.basename(path)
    name = rdf_filename.split('.')[0]
    element = {
        "id": name,
        "name": name,
        "type": "include",
        "url": rdf_filename
    }
    rdf["elements"][name] = element
    rdf["root"]["children"].append(name)

print(json.dumps(rdf))

